/**! --------------------------------------------------------------------------------------
 *   Copyright (c) Liu Yue @hangxingliu. All rights reserved.
 *   Licensed under the MIT License. Details in `LICENSE` file in the project root.
 *   Authors:  Liu Yue <hangxingliu@gmail.com>
 *   ORCID:    https://orcid.org/0009-0007-6518-185X
 *   --------------------------------------------------------------------------------------   */
import { writeFile } from "fs/promises";
import { dirname } from "path";
import type { Options } from "prettier";

export function getBannerForGeneratedCode(generator: string, commentType = "// "): string {
  return [
    //
    `${commentType} CAVEAT:`,
    `${commentType} Code generated by ${generator}; DO NOT EDIT.`,
    ``,
  ].join("\n");
}

export async function formatTypeScriptCode(
  code: string,
  targetFile: string,
  writeTo?: boolean,
  prettierOpts?: Options
) {
  const prettier = await import("prettier");

  /** Determine the starting directory based on the target file path */
  const targetDir = dirname(targetFile);
  if (!prettierOpts) {
    const resolved = await prettier.resolveConfig(targetDir);
    if (!resolved) throw new Error(`Failed to resolve the Prettier config file for "${targetFile}"`);
    prettierOpts = resolved;
  }
  if (!prettierOpts.parser) prettierOpts.parser = "typescript";

  try {
    code = await prettier.format(code, prettierOpts);
  } catch (error) {
    const errMsg = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to format the source code: ${errMsg}`);
  }

  try {
    if (writeTo) {
      await writeFile(targetFile, code);
      process.stderr.write(`generated "${targetFile}"\n`);
    }
  } catch (error) {
    const errMsg = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to generate the file "${targetFile}": ${errMsg}`);
  }

  return { code, prettierOpts };
}
